Azure pipeline support for arm64 using qemu
aio-libs/azure-pipelines pull request #1
Opened 2020-10-07 07:30 UTC by odidev

Added azure pipeline support for arm64 builds using qemu.
Rework for review [comment](https://github.com/aio-libs/multidict/pull/519#pullrequestreview-495544375).
@webknjaz Could you please review the changes?

2020-10-11 20:40 UTC, webknjaz requested changes

2020-10-11 20:40 UTC, webknjaz commented on templates/stage-deploy-aarch64.yml
> +        Py38 Arm64:
Does this image have CPython 3.9 in it?

2020-10-11 20:40 UTC, webknjaz commented on templates/stage-deploy-aarch64.yml
> +stages:
Looks like it's just a hardcoded pipeline. It's a template repo and it should contain only parametrized bits while the repos that use the templates would specify those params, like CPython versions.

2020-11-16 10:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aio-libs/azure-pipelines?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aio-libs/azure-pipelines?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aio-libs/azure-pipelines?pullRequest=1) it.</sub>

2020-11-16 22:29 UTC, asvetlov commented
Sorry, what project do you want to use the PR for? Yarl is already built with aarch64 support, isn't it.

2020-11-17 06:13 UTC, odidev commented
@asvetlov I had raised this PR to add wheel support for aarch64 as per review comment [#discussion_r472823287](https://github.com/aio-libs/multidict/pull/519#discussion_r472823287). But this is not required now as multidict and yarl are using github actions for building wheels. So, closing this PR. Thanks.

2020-11-17 06:13 UTC, closed without merging